<?php
/**
 * @file
 * Debugs session and logs to JavaScript console.
 *
 * To configure log files run the following command from root of Drupal site
 * amending log file paths as appropriate:
 * drush vset browser_debug_logs "/var/log/one.log,/var/log/two.log"
 */

/**
 * Implements hook_boot().
 *
 * Gather log positions.
 */
function browser_debug_boot() {
  // var_dump('-boot-');
  require_once 'BrowserDebug.php';
  $browser_debug = BrowserDebugFactory::getBrowserDebug();
  if (!isset($browser_debug)) {
    $browser_debug = new BrowserDebug();
  }
}

/**
 * Implements hook_ajax_render_alter().
 *
 * Add our own completion command to trigger client side actions.
 */
function browser_debug_ajax_render_alter(&$commands) {
  // var_dump('-ajax-');
  $browser_debug = BrowserDebugFactory::getBrowserDebug();
  $commands[] = array('command' => 'browserDebugAjaxComplete', 'arguments' => $browser_debug->getAllData());
}

/**
 * Implements hook_js_alter().
 *
 * Populate client side data in Drupal.settings.
 */
function browser_debug_page_build() {
  // var_dump('-build-');
  $browser_debug = BrowserDebugFactory::getBrowserDebug();
  drupal_add_js(array('browserDebug' => $browser_debug->getAllData()), 'setting');
}

/**
 * Logs to javascript console.
 *
 * @param mixed $item
 *   Item to log.
 * @param string $label
 *   Label to display next to item.
 */
function bd($item, $label = '') {
  $browser_debug = BrowserDebugFactory::getBrowserDebug();
  $browser_debug->log($item, $label);
}
